version: "3.8"
services:
  rp:
    build: ./rp
    ports:
      - 3000:3000
    depends_on:
      - keycloak
    extra_hosts:
      - localhost:[YOUR_LOCAL_IP]
  keycloak:
    build: ./keycloak
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import